services:
  # CockroachDB Database
  cockroachdb:
    image: cockroachdb/cockroach:v23.2.0
    container_name: musicschool-db
    command: start-single-node --insecure --http-addr=0.0.0.0:8080 --listen-addr=0.0.0.0:26257
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    environment:
      - COCKROACH_DATABASE=musicschool
      - COCKROACH_DEVELOPER_MODE=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - musicschool-network

  # Music School Application
  musicschool-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musicschool-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=root
      - DB_PASSWORD=
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cockroachdb:26257/musicschool?sslmode=disable
      - ADMIN_PASSWORD=admin123
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - MANAGEMENT_HEALTH_MAIL_ENABLED=false
      - MAIL_HOST=mock-email-server
      - MAIL_PORT=1025
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
    depends_on:
      cockroachdb:
        condition: service_healthy
      redis:
        condition: service_healthy
      mock-email-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - musicschool-network

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: musicschool-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - musicschool-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: musicschool-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - musicschool-network

  # Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: musicschool-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - musicschool-network

  # Custom Mock Email Server for development and testing
  mock-email-server:
    build:
      context: ./mock-email-server
      dockerfile: Dockerfile
    container_name: musicschool-mock-email
    ports:
      - "3001:3000"  # Web UI port
      - "1025:1025"  # SMTP port
    environment:
      - PORT=3000
      - SMTP_PORT=1025
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/health" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - musicschool-network

  flyway:
    image: flyway/flyway:10
    command: -url=jdbc:postgresql://cockroachdb:26257/musicschool?sslmode=disable -user=root -password= -connectRetries=20 -baselineOnMigrate=true migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      cockroachdb:
        condition: service_healthy
    restart: on-failure
    networks:
      - musicschool-network

volumes:
  cockroach-data:
  grafana-data:
  redis-data:

networks:
  musicschool-network:
    driver: bridge
