spring:
  application:
    name: music-school-management
  datasource:
    url: jdbc:postgresql://localhost:26257/musicschool?sslmode=disable
    username: ${DB_USERNAME:musicschool}
    password: ${DB_PASSWORD:musicschool123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cache:
    type: jcache
    jcache:
      config: classpath:ehcache.xml
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,beans,env,configprops
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    com.musicschool: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/music-school.log

vaadin:
  productionMode: false
  closeIdleSessions: true
  heartbeatInterval: 300

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true

jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: 86400

stripe:
  secret-key: ${STRIPE_SECRET_KEY:sk_test_...}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:pk_test_...}

multitenancy:
  default-tenant: default
  tenant-header: X-Tenant-ID
  tenant-parameter: tenant
